### ISSUE TITLE
Возможность закрыть приложение без остановки воспроизведения

### ISSUE THREAD

**Issue by BorisYeltsin** [oniksfly/YaMusic#10]
Достаточно банальная идея для следующего обновления. Есть ли такая возможность сделать так, что бы при нажатии на крестик, приложение не закрывалось полностью, а закрывалось лишь само окно приложения, при этом приложение продолжало работу в фоновом режиме? Так реализовано, например, в iTunes или программах Adobe.

**Comment by oniksfly** [comment]
Привет! В настройках приложения, начиная с версии 1.7 теперь можно указать, как будет вести себя приложение при закрытии главного окна.
