### ISSUE TITLE
Проблема в 1.6.1 с пустым экраном осталась

### ISSUE THREAD

**Issue by emelvit** [oniksfly/YaMusic#11]
У меня последний релиз не исправил проблему из-за которой не открывался интерфейс Яндекс.Музыки при запуске приложения. Видно, что загружается, но через долю секунды пропадает и остается пустой экран. MacOS 10.14.5

**Comment by oniksfly** [comment]
А до этого были авторизованы в сервисе? У вас есть подписка Плюс?

**Comment by emelvit** [comment]
Был. Есть +

**Comment by oniksfly** [comment]
Решено во второй вресии
