### ISSUE TITLE
Проблема при звонках и паузах

### ISSUE THREAD

**Issue by sergeyklochko** [oniksfly/YaMusic#12]
Если во время воспроизведении композиции, приходит звонок, или происходит какое-то другое событие, которое ставит воспроизведение на паузу, то невозможно возобновить проигрывание трека - прогресс идет, секунды считаются, но звука нет. Если нажать следующий трек, все нормализуется. Но в итоге невозможно дослушать трек. В браузере все нормально.

**Comment by ruslan-matrix** [comment]
Аналогичная проблема только что воспроизвелась, когда писал про другой баг.

**Comment by png2378** [comment]
Подтверждаю. 

Тоже самое, если слушать музыку в AirPods, а затем вытащить наушник – трек становится на паузу, но воспроизводится дальше отказывается.

**Comment by oniksfly** [comment]
Решено во второй версии
