### ISSUE TITLE
The use of the built-in buttons for changing the sound level leads to the crash

### ISSUE THREAD

**Issue by elejke** [oniksfly/YaMusic#15]
The use of the built-in buttons for changing the sound level (**command + F11/F12**) leads to the crash of the application.

System specs: 
- **Mac OS version: 10.15.3 (19D76)**
- **MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)**
- **Processor: 2,3 GHz Dual-Core Intel Core i5**
- **Yamusic version: 1.7 (3)**

**Comment by elejke** [comment]
Discovered that it only crashes when Air Pods used

**Comment by oniksfly** [comment]
Fixed in version 2.0
