### ISSUE TITLE
Expired token

### ISSUE THREAD

**Issue by realabs** [oniksfly/YaMusic#16]
При авторизации со своим логином и паролем получаю сообщение "expired_token"
<img width="409" alt="Screenshot 2020-08-25 at 15 21 30" src="https://user-images.githubusercontent.com/1265306/91173593-bf071380-e6e6-11ea-951d-171565c4a31a.png">

**Comment by BorisYeltsin** [comment]
все то же самое

**Comment by BorisYeltsin** [comment]
почините, пожалуйста! Каждый день захожу, жду апдейта. Очень интересно что же там в новой версии!

**Comment by realabs** [comment]
Плюсую. Откатился на старую версию, но она работает ужасно и каждый раз запускает System Settings зачем-то. Всё жду апдейта, но уже думаю, что авторам приложение больше не нужно, к сожалению.

**Comment by BorisYeltsin** [comment]
в списке авторизованных приложений яндекса, данное приложение числится, токен авторизации сервисом выдается. С временным паролем ya.key тоже работает, но все равно выдается ошибка просроченного токена. Видимо, проблема внутри приложения

**Comment by anton-trf** [comment]
Аналогичная проблема, токен Я тоже выдает

> в списке авторизованных приложений яндекса, данное приложение числится, токен авторизации сервисом выдается. С временным паролем ya.key тоже работает, но все равно выдается ошибка просроченного токена. Видимо, проблема внутри приложения

**Comment by oniksfly** [comment]
У Яндекса нет публичного API для работы с музыкой, поэтому как такового зарегистрированного приложения для этого сервиса сейчас быть не может. 

В последней сборке обновлён временный ключ доступа - через какое-то время он перестанет действовать. Нужно будет зареверсить механизм получения токена в приложении.

[Версия 2.0.1 (2.0 сборка 11)](https://github.com/oniksfly/YaMusic/releases/tag/2.0.1)
