### ISSUE TITLE
Сырое, но крутое

### ISSUE THREAD

**Issue by icedogas** [oniksfly/YaMusic#20]
Привет ребят, спасибо за попытку - но приложение очень сырое - поставил и пока пробовал просто послушать плейлист дня вываливалось с ошибками раза 4, вернусь как станет более стабильным - а вам удачи, надеюсь у вас все получиться)
И еще хотелось бы глобальных горячих кнопок - следующая, пауза, лайк, дизлайк, не на медиа кнопках

**Comment by oniksfly** [comment]
Привет! Спасибо, но проект не будет дальше развиваться.
