### ISSUE TITLE
Не работает возобновление воспроизведение через AirPods

### ISSUE THREAD

**Issue by R0dgerV** [oniksfly/YaMusic#4]
Не работает возобновление проигрывания через AirPods, при двойном прикосновении воспроизведение успешно останавливается, но если еще раз сделать двойное прикосновение, ничего не происходит. Не очень удобно приходится снова идти в окно программы или с клавиатуры запускать. macOs High Sierra

**Comment by oniksfly** [comment]
Боюсь, что пока не приобрету себе их, не удастся реализовать эту возможность

https://apple.stackexchange.com/questions/283809/can-airpods-double-tap-to-play-pause-be-made-to-work-in-other-macos-application

**Comment by elejke** [comment]
@oniksfly, если бы ты выложил исходный код, я бы, возможно, попробовал пофиксить данную проблему

**Comment by oniksfly** [comment]
@elejke займусь этим в ближайшее время.

**Comment by png2378** [comment]
Также не работает переключение на следующий/предыдущий трек по двойному тапу.

**Comment by pyzho** [comment]
Спасибо за приложение! Присоединяюсь – отсутствие управления перелистыванием и паузой с AirPods - единственный для меня минус использования Яндекс музыкой на Mac. С Apple music в этом плане всё было удобно.

**Comment by oniksfly** [comment]
Решено во второй версии.
