### ISSUE TITLE
не меняется окраска сердечка, когда лайкаешь/дизлайкаешь текущий трек в плеере снизу

### ISSUE THREAD

**Issue by sergeyklochko** [oniksfly/YaMusic#6]
Иногда не меняется окраска сердечка, когда лайкаешь/дизлайкаешь текущий трек в плеере внизу экрана. Условия воспроизведения установить не получилось. При перезапуске вылечилось.
![image](https://user-images.githubusercontent.com/37343789/55420770-7b0af000-5580-11e9-9e5d-73b419a4ecf6.png)

**Comment by oniksfly** [comment]
А при добавлении/исключении из избранного, в случае, когда не меняется цвет сердечка, отображается сообщение об успешности операции?

<img width="398" alt="Screenshot 2019-04-04 at 17 12 37" src="https://user-images.githubusercontent.com/5785870/55562641-0c9f6c80-56fd-11e9-9703-5f5666be21da.png">

**Comment by sergeyklochko** [comment]
Проблема воспроизводится условно стабильно, но условия все еще непонятны. Похоже связана с тем, что приложение теряет фокус. Сегодня воспроизвелась через 15 минут после перезагрузки, когда я ткнул в сердечко неактивного окна. переключилось в окно, и второй клик как раз не меняя цвет дал сообщение о том, что трек добавлен. Я нажал reload и проверил еще раз - не воспроизвелось. Видимо есть какое-то дополнительное условие.

**Comment by oniksfly** [comment]
Удалось воспроизвести поведение. При лайке трека html-элемент `.player-controls__track-controls .d-like` не получает класс `d-icon_heart-full`. Но поведение спорадическое, после перезагрузки ни разу не удалось повторить такое поведение. Ещё понаблюдаю за этой проблемой.

**Comment by oniksfly** [comment]
Решено во второй версии
