### ISSUE TITLE
Получить название песни

### ISSUE THREAD

**Issue by utya1988** [oniksfly/YaMusic#7]
Подскажите как с помощью скрипта выцепить название песни, title выдает mp3 ссылку

**Comment by utya1988** [comment]
использую better touch tool

**Comment by oniksfly** [comment]
К сожалению, не смогу подсказать, поскольку нет опыта работы с BTT.

**Comment by utya1988** [comment]
подскажите как с помощью apple script можно выцепить эту инфу. спасибо

**Comment by oniksfly** [comment]
Приложение не использует Apple Script, только обычный JS. А что вы пытаетесь сделать?

**Comment by utya1988** [comment]
Я с помощью apple script пытаюсь выцепить название трека, как это сделать с
браузера я понял, нужно найти переменную title, в браузере с сайта яндек
музыки все нормально, Но из приложения возвращает путь на mp3. Пытался
перехватить из push уведомления. Но я не знаю как. Вообщем пока гуглю, как
с помощью apple script получить все мозможные атрибуты из приложений

чт, 18 апр. 2019 г., 18:05 Ilya <notifications@github.com>:

**Comment by oniksfly** [comment]
Бегло посмотрел возможность передачи данных из самого приложения в Apple Script без костылей, но явного ответа не нашёл. Если с костылями, то можно добавить в заголовок окна приложения название воспроизводимого трека ограниченной длины, думаю AS умеет такие атрибуты читать. 

Но вы не ответили зачем вам это нужно, возможно вашу задачу стоит решить средствами приложения.

**Comment by utya1988** [comment]
у меня приложение better touch tool, в нем делаю правила которое собирает информацию о проигрываемом треке https://vas3k.ru/blog/touchbar/ у него есть стандартный плагин которы вытягивает инфу с Itunes, spootify. Для яндекс музыки он вытягивает с ошибками.

**Comment by victordidenko** [comment]
+1
хочется отображать текущий играющий трек на тачбар
