### ISSUE TITLE
Иногда не проигрываются треки

### ISSUE THREAD

**Issue by BorisYeltsin** [oniksfly/YaMusic#8]
Иногда, совершенно спонтанно перестают проигрываться песни при переключении на следующую. Вся индикация показывает, что трек проигрывается, таймлайн ползет, но звука нет, как будто не подключены наушники. Вылечивается переключением назад и вперед.

**Comment by oniksfly** [comment]
@BorisYeltsin а у вас в браузере такое не наблюдается? У меня пару раз так случалось, поэтому могу только предположить, что это проблема в самой Я.Музыке.

**Comment by ruslan-matrix** [comment]
У меня тоже самое.
MacOS 10.13.6
В браузере всегда играет.
Приходится переходить к следующему треку.

**Comment by oniksfly** [comment]
Решено во второй версии
