### ISSUE TITLE
Перестало работать

### ISSUE THREAD

**Issue by BorisYeltsin** [oniksfly/YaMusic#9]
Добрый день! Сегодня все сломалось, выдает бланковую страницу, если потыкать, то можно дойти до страницы с просьбой предоставить доступ к аккаунту и дальше зависает. Удалял полностью со всеми хвостами, переустанавливал и все то же самое. Яндекс прикрыл доступ или что-то другое случилось?

**Comment by oniksfly** [comment]
Добрый день! Решаю эту проблему, спасибо за обратную связь.

**Comment by oniksfly** [comment]
@BorisYeltsin [новый релиз](https://github.com/oniksfly/YaMusic/releases/tag/1.6.1) должен решить эту проблему.

**Comment by BorisYeltsin** [comment]
Спасибо огромное! Все заработало!

**Comment by BorisYeltsin** [comment]
а медиа клавиши случайно не сломались?

**Comment by oniksfly** [comment]
Проверьте, пожалуйста: Настройки → Защита и безопасность (вкладка «Конфиденциальность») → Универсальный доступ

Для YaMusic должна стоять галочка.

**Comment by BorisYeltsin** [comment]
стояла, удалил, добавил заново и перезапустил приложение. Заработало, спасибо!
